import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFile,readdir} from 'node:fs/promises';
import {buildProfile,sampleAnswers,stages,demoAnswers,demoPlan,validatePlan,scenarioPlan,parseModelJSON,validateExperienceEvidence,requiredQuestions,activeQuestions} from '../public/core.js';
import {guardResult,analyze,evidenceForProfile} from '../src/ai.mjs';
import {evidence} from '../public/evidence.js';
import {emptyStore,cleanRecord,decodeStore,writeStore,collectExperience,storageKey,migrateLegacy,planChanges} from '../public/storage.js';
import {acquireJob,cleanup,saveAction,savePlan} from '../src/db.mjs';
import worker from '../build/worker.js';
import {createWorkQueue} from '../public/sync.js';
const ids=evidence.sources.map(s=>s.id),plan=()=>demoPlan(demoAnswers);
class D1TestDB{
 constructor(){this.sql=new DatabaseSync(':memory:');this.sql.exec('PRAGMA foreign_keys=ON');}
 prepare(query){const db=this;return {args:[],bind(...args){this.args=args;return this;},async run(){const r=db.sql.prepare(query).run(...this.args);return {meta:{changes:Number(r.changes)},success:true};},async first(){return db.sql.prepare(query).get(...this.args)||null;},async all(){return {results:db.sql.prepare(query).all(...this.args)};}};}
 async batch(statements){this.sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());this.sql.exec('COMMIT');return results;}catch(e){this.sql.exec('ROLLBACK');throw e;}}
}
async function database(){const db=new D1TestDB();for(const f of (await readdir(new URL('../migrations/',import.meta.url))).sort())db.sql.exec(await readFile(new URL('../migrations/'+f,import.meta.url),'utf8'));return db;}
async function session(db,id='owner'){await db.prepare('INSERT INTO sessions(id,created_at,expires_at) VALUES(?,?,?)').bind(id,new Date().toISOString(),new Date(Date.now()+86400000).toISOString()).run();return id;}
const records=[{routeId:'practice',routeTitle:'实践方向',completed:[0],notes:{source:'课程项目',proof:'运行说明',feedback:'更喜欢用户访谈，希望比较设计方向',next:'收到同学的反馈'}}];
async function harness(extra={}){const db=await database(),env={DB:db,API_KEY:'test-only',...extra},tasks=[],ctx={waitUntil:p=>tasks.push(p)};let cookie='';const request=async(path,body,method=body?'POST':'GET')=>{const r=await worker.fetch(new Request('https://local.test'+path,{method,headers:{Origin:'https://local.test','Content-Type':'application/json',Cookie:cookie},...(body?{body:JSON.stringify(body)}:{})}),env,ctx);if(r.headers.get('Set-Cookie'))cookie=r.headers.get('Set-Cookie').split(';')[0];return r;};await request('/api/state');return {db,request,close:async()=>{await Promise.allSettled(tasks);db.sql.close();}};}
const liveBody=()=>({answers:demoAnswers,confirmed:true,aiConsent:true,persist:true,requestId:crypto.randomUUID(),experienceEvidence:records});
function modelReply(init){const b=JSON.parse(init.body),input=JSON.parse(b.messages[1].content);return Response.json({model:b.model,choices:[{message:{content:JSON.stringify(input.independent_opinions?plan():{summary:'优先用真实任务验证方向。',preferred:'就业验证',risks:['机会有效期需核实'],missing:['实习时间未落实'],evidence_ids:['java'],routes:[{title:'就业验证',feasibility:'可以先核对任务，不认定已获得机会',development:'以可展示成果与反馈检验就业选择',risk:'实际岗位资格仍待核实',lever:'补齐个人贡献的证据',evidence_ids:['java']},{title:'继续深造',feasibility:'准备窗口与当年资格待核实',development:'通过研究体验判断长期投入意愿',risk:'准备期的时间与经济成本',lever:'落实准备窗口并验证研究体验',evidence_ids:['study_policy']}]})}}]});}
test('五个入口、八类领域均可生成三条合法路线，不把早期用户套入求职',()=>{for(const stage of stages.map(s=>s.value)){for(const major of ['cs','related','design','business','humanities','science','health','other']){const answers={...sampleAnswers(stage),major};if(['cs','related'].includes(major))answers.direction='unsure';const p=demoPlan(answers);assert.equal(p.routes.length,3);assert.equal(p.routes.filter(r=>r.level==='primary').length,1);assert.doesNotThrow(()=>guardResult(p,buildProfile(answers).answers));if(['school','early'].includes(stage))assert(!p.routes.some(r=>r.evidence_ids.length));}}});
test('来源、门槛和时间不能靠省略标签绕过',()=>{let p=plan();p.routes[0].evidence_ids=[];assert.throws(()=>guardResult(p,demoAnswers),/缺少来源/);p=plan();p.routes[1].title='探索外地的进阶机会';p.routes[1].gates=[];assert.throws(()=>guardResult(p,demoAnswers),/标签不一致/);p=plan();p.routes[0].action.effort_hours=20;assert.throws(()=>guardResult(p,{...demoAnswers,hours:'5'}),/超过/);p=plan();p.routes[0].action.hours='每周 20 小时';assert.throws(()=>guardResult(p,{...demoAnswers,hours:'5'}),/不一致/);p=plan();p.routes[0].id='__proto__';assert.throws(()=>validatePlan(p,ids),/标识/);});
test('代码围栏可解析，路线标题去空白后仍须不同',()=>{const fence=String.fromCharCode(96).repeat(3);assert.deepEqual(parseModelJSON(fence+'json\n{"ok":true}\n'+fence),{ok:true});const p=plan();p.routes[1].title=p.routes[0].title+' ';assert.throws(()=>validatePlan(p,ids),/重复/);});
test('情景预览保留真实路线身份、理由和排序，不复用模型意见',()=>{const p={...plan(),mode:'live',committee:[{provider:'test',summary:'old'}],decision:{model:'test'}};const before=structuredClone(p),a=structuredClone(demoAnswers);const next=scenarioPlan(a,'away',p);assert.deepEqual(p,before);assert.deepEqual(a,demoAnswers);assert.deepEqual(next.routes.map(r=>[r.id,r.why,r.level]),p.routes.map(r=>[r.id,r.why,r.level]));assert.equal(next.mode,'preview');assert.deepEqual(next.committee,[]);assert.equal(next.decision,undefined);});
test('重规划记录进入所有模型输入，保留为用户陈述',async()=>{const inputs=[];const result=await analyze(demoAnswers,{API_KEY:'test-only'},()=>{},new AbortController().signal,async(u,init)=>{const b=JSON.parse(init.body),input=JSON.parse(b.messages[1].content);inputs.push(input);return Response.json({model:b.model,choices:[{message:{content:JSON.stringify(input.independent_opinions?plan():{summary:'优先用真实任务验证方向。',preferred:'就业验证',risks:['机会有效期需核实'],missing:['实习时间未落实'],evidence_ids:['java'],routes:[{title:'就业验证',feasibility:'可以先核对任务，不认定已获得机会',development:'以可展示成果与反馈检验就业选择',risk:'实际岗位资格仍待核实',lever:'补齐个人贡献的证据',evidence_ids:['java']},{title:'继续深造',feasibility:'准备窗口与当年资格待核实',development:'通过研究体验判断长期投入意愿',risk:'准备期的时间与经济成本',lever:'落实准备窗口并验证研究体验',evidence_ids:['study_policy']}]})}}]});},records);assert.equal(inputs.length,4);for(const i of inputs){assert.deepEqual(i.experience_evidence,records);assert.match(i.evidence_scope,/用户陈述/);}assert.deepEqual(result.experienceEvidence,records);});
test('超长或无效行动证据被拒绝',()=>{assert.throws(()=>validateExperienceEvidence({}));assert.throws(()=>validateExperienceEvidence([{...records[0],notes:{feedback:'字'.repeat(1201)}}]));assert.throws(()=>validateExperienceEvidence([{...records[0],completed:[-1]}]));});
test('本地规划、行动与旧版本可序列化；其他标签页的新版不会被覆盖',()=>{const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};const s=emptyStore(),record=cleanRecord({id:crypto.randomUUID(),answers:demoAnswers,result:plan(),work:{practice:{completed:[0],notes:records[0].notes}},created:new Date().toISOString()});s.plans.push(record);s.activeId=record.id;writeStore(storage,s);const restored=decodeStore(storage.getItem(storageKey));const collected=collectExperience(restored.plans[0]);assert.deepEqual(collected[0].notes,records[0].notes);assert.deepEqual(collected[0].completed,[0]);const stale=structuredClone(restored);writeStore(storage,restored);assert.throws(()=>writeStore(storage,stale),/另一标签页/);assert.equal(JSON.parse(storage.getItem(storageKey)).revision,2);assert.throws(()=>decodeStore('{broken'));});
test('跨实例请求锁只允许同一会话一个分析，过期后可恢复',async()=>{const db=await database();try{await session(db);const results=await Promise.all([acquireJob(db,'owner',crypto.randomUUID(),'a'),acquireJob(db,'owner',crypto.randomUUID(),'b')]);assert.equal(results.filter(x=>x.acquired).length,1);db.sql.exec('UPDATE planning_jobs SET expires_at=0');assert((await acquireJob(db,'owner',crypto.randomUUID(),'new')).acquired);}finally{db.sql.close();}});
test('行动乐观锁拒绝旧版本与跨会话修改',async()=>{const db=await database();try{await session(db);await session(db,'other');const p=await savePlan(db,'owner',demoAnswers,plan());const body={routeId:'practice',completed:[0],notes:{proof:'作品'},revision:0};assert.equal((await saveAction(db,'owner',p.id,body)).revision,1);assert.equal((await saveAction(db,'owner',p.id,body)).reused,true);await assert.rejects(()=>saveAction(db,'owner',p.id,{...body,notes:{proof:'旧版本的不同修改'}}),/其他标签页/);await assert.rejects(()=>saveAction(db,'other',p.id,body),/不属于/);}finally{db.sql.close();}});
test('过期清理不会只处理前一百条',async()=>{const db=await database();try{for(let i=0;i<250;i++)db.sql.prepare('INSERT INTO sessions VALUES(?,?,?)').run('expired-'+i,'2020-01-01','2020-01-02');await session(db);const r=await cleanup(db);assert.equal(r.removed,250);assert.equal(db.sql.prepare('SELECT COUNT(*) n FROM sessions').get().n,1);}finally{db.sql.close();}});
test('Worker 配置不创建会话；游客演示不持久化画像，云端操作必须主动同意',async()=>{const db=await database(),env={DB:db};const tasks=[],ctx={waitUntil:p=>tasks.push(p)},origin='https://local.test';try{let r=await worker.fetch(new Request(origin+'/api/config'),env,ctx);assert.equal(r.status,200);assert.equal(db.sql.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);const body={answers:demoAnswers,confirmed:true,persist:false};r=await worker.fetch(new Request(origin+'/api/demo',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)}),env,ctx);assert.equal(r.status,200);assert.equal((await r.json()).plan.routes.length,3);assert.equal(db.sql.prepare('SELECT COUNT(*) n FROM plans').get().n,0);assert.equal(db.sql.prepare('SELECT COUNT(*) n FROM drafts').get().n,0);r=await worker.fetch(new Request(origin+'/api/draft',{method:'PUT',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({answers:demoAnswers})}),env,ctx);assert.equal(r.status,400);r=await worker.fetch(new Request(origin+'/api/demo',{method:'POST',headers:{Origin:'https://elsewhere.test','Content-Type':'application/json'},body:JSON.stringify(body)}),env,ctx);assert.equal(r.status,403);}finally{await Promise.allSettled(tasks);db.sql.close();}});

test('连续编辑不同路线不会互相取消云端保存，失败后队列仍可继续',async()=>{const sent=[],failed=[];const queue=createWorkQueue(async(id,route)=>{sent.push(id+':'+route);if(route==='failed')throw Error('模拟故障');},e=>failed.push(e.message),60000);queue.enqueue('a','practice');queue.enqueue('a','study');queue.enqueue('a','practice');await queue.flush();assert.deepEqual(sent,['a:practice','a:study']);queue.enqueue('a','failed');queue.enqueue('a','adjacent');await queue.flush();assert.equal(failed.length,1);assert.equal(sent.at(-1),'a:adjacent');queue.enqueue('a','canceled');queue.cancel();await queue.flush();assert(!sent.includes('a:canceled'));});
test('示例体验备份与未同步状态可恢复，超量缓存不静默截断',()=>{const state=emptyStore();state.sampleBackup={answers:sampleAnswers('school'),index:2,confirmed:false,mode:'demo',replanEvidence:[]};state.plans=[cleanRecord({id:crypto.randomUUID(),answers:demoAnswers,result:plan(),work:{practice:{pending:true}}})];const decoded=decodeStore(JSON.stringify(state));assert.equal(decoded.sampleBackup.answers.stage,'school');assert.equal(decoded.plans[0].work.practice.pending,true);state.plans=Array(31).fill(state.plans[0]);assert.throws(()=>decodeStore(JSON.stringify(state)),/30/);assert.throws(()=>cleanRecord({id:'" onclick="bad',answers:demoAnswers,result:plan()}),/格式/);});
test('另一个标签页清空资料后，不会悄悄把旧资料写回',()=>{const store=emptyStore();store.revision=4;assert.throws(()=>writeStore({getItem:()=>null},store),/清除/);});
test('Worker 完整流式分析保存结果，重复请求复用结果且不重复调用模型',async t=>{let calls=0;t.mock.method(globalThis,'fetch',async(u,init)=>{calls++;return modelReply(init);});const h=await harness();try{const body=liveBody();let r=await h.request('/api/plan',body);assert.equal(r.status,200);assert.match(r.headers.get('Content-Type'),/ndjson/);const events=(await r.text()).trim().split('\n').map(JSON.parse),last=events.at(-1);assert.equal(last.type,'result');assert.equal(last.plan.routes.length,3);assert.equal(calls,4);assert(last.planId);r=await h.request('/api/plan',body);const reused=await r.json();assert.equal(reused.reused,true);assert.equal(reused.planId,last.planId);assert.equal(calls,4);assert.equal((await (await h.request('/api/plans/'+last.planId)).json()).result.mode,'live');}finally{await h.close();}});
test('Worker 同会话并发请求只执行一轮，完成后释放数据库锁',async t=>{let release;const gate=new Promise(r=>release=r);t.mock.method(globalThis,'fetch',async(u,init)=>{await gate;return modelReply(init);});const h=await harness();try{const r=await h.request('/api/plan',liveBody());const duplicate=await h.request('/api/plan',liveBody());assert.equal(duplicate.status,409);release();assert.equal(JSON.parse((await r.text()).trim().split('\n').at(-1)).type,'result');assert.equal(h.db.sql.prepare("SELECT COUNT(*) n FROM planning_jobs WHERE status='running'").get().n,0);}finally{release();await h.close();}});
test('云端写入失败不会丢弃已完成的模型结果',async t=>{t.mock.method(globalThis,'fetch',async(u,init)=>modelReply(init));const h=await harness();try{const original=h.db.prepare.bind(h.db);h.db.prepare=q=>{if(q.startsWith('INSERT INTO plans'))throw Error('模拟保存中断');return original(q);};const r=await h.request('/api/plan',liveBody());const last=JSON.parse((await r.text()).trim().split('\n').at(-1));assert.equal(last.type,'result');assert.equal(last.planId,null);assert.match(last.storageWarning,/保存失败/);assert.equal(last.plan.routes.length,3);}finally{await h.close();}});
test('模型鉴权失败明示错误、不伪造规划、不遗留运行锁',async t=>{t.mock.method(globalThis,'fetch',async()=>Response.json({error:{message:'no auth'}},{status:401}));const h=await harness();try{const r=await h.request('/api/plan',liveBody());const events=(await r.text()).trim().split('\n').map(JSON.parse);assert.equal(events.at(-1).type,'error');assert(!events.some(e=>e.type==='result'));assert.equal(h.db.sql.prepare('SELECT COUNT(*) n FROM plans').get().n,0);assert.equal(h.db.sql.prepare("SELECT COUNT(*) n FROM planning_jobs WHERE status='running'").get().n,0);}finally{await h.close();}});
test('Worker 云端规划与行动接口隔离会话，并拒绝未确认的 AI 请求',async()=>{const h=await harness();try{let r=await h.request('/api/plan',{...liveBody(),aiConsent:false});assert.equal(r.status,400);r=await h.request('/api/demo',{answers:demoAnswers,confirmed:true,persist:true});const saved=await r.json();r=await worker.fetch(new Request('https://local.test/api/plans/'+saved.id),{DB:h.db},{});assert.equal(r.status,404);r=await worker.fetch(new Request('https://local.test/api/plans/'+saved.id+'/actions',{method:'PUT',headers:{Origin:'https://local.test','Content-Type':'application/json'},body:JSON.stringify({routeId:'practice',completed:[],notes:{},revision:0})}),{DB:h.db},{});assert.equal(r.status,400);}finally{await h.close();}});

test('旧版访谈与行动可以迁移；保留旧缓存且不自动续传云端',()=>{const old={answers:demoAnswers,result:plan(),planId:crypto.randomUUID(),tasks:{'practice-0':true},worksheet:{'practice-feedback':'旧版体验'},revisions:{practice:4},mode:'live'};const raw=JSON.stringify(old),migrated=migrateLegacy(raw);assert.equal(migrated.plans[0].work.practice.notes.feedback,'旧版体验');assert.deepEqual(migrated.plans[0].work.practice.completed,[0]);assert.equal(migrated.plans[0].remoteId,null);assert.equal(migrated.confirmed,false);assert.equal(JSON.stringify(old),raw);assert.doesNotThrow(()=>decodeStore(JSON.stringify(migrated)));});


test('访谈先围绕真实问题，关键资料齐备后允许停止且不虚构补充答案',()=>{
 const answers={...sampleAnswers('early')};delete answers.grades;delete answers.direction;
 assert.deepEqual(activeQuestions(answers).slice(0,3).map(q=>q.id),['stage','concern','major']);
 assert(requiredQuestions(answers).every(q=>answers[q.id]));
 const profile=buildProfile(answers);assert(!('grades' in profile.answers));assert(!('direction' in profile.answers));assert(!profile.facts.some(f=>f.id==='grades'));
 assert(profile.coreConflict&&profile.lever);assert.equal(profile.inferences[0].user_confirmed,false);
});
test('画像、推荐与第一步响应领域、城市和经济边界，研究体验影响主推荐',()=>{
 const base=plan(),design=demoPlan({...demoAnswers,major:'design',city:'杭州'}),urgent=demoPlan({...demoAnswers,finance:'urgent'});
 assert.notEqual(base.summary,design.summary);assert.match(design.summary,/杭州.*设计/);assert.match(design.lever,/设计/);assert.deepEqual(design.routes[0].evidence_ids,[]);
 assert.match(urgent.summary,/收入/);assert.equal(urgent.routes.find(r=>r.id==='study').level,'locked');
 const research=demoPlan({...demoAnswers,priority:'research',research:'tested',finance:'6m'});assert.equal(research.routes.find(r=>r.level==='primary').id,'study');
});
test('解除单一条件会解锁，其他未满足门槛仍阻挡；预览不修改主推荐与历史',()=>{
 const answers={...sampleAnswers('senior'),relocation:'no',availability:'yes'},base=demoPlan(answers),snapshot=structuredClone(base),next=scenarioPlan(answers,'away',base);
 assert.equal(base.routes.find(r=>r.id==='adjacent').level,'locked');assert.equal(next.routes.find(r=>r.id==='adjacent').level,'alternative');assert(next.preview.changes.some(c=>c.unlocked));
 assert.equal(next.routes.find(r=>r.level==='primary').id,base.routes.find(r=>r.level==='primary').id);assert.deepEqual(base,snapshot);
 const blocked=scenarioPlan(demoAnswers,'away',plan());assert.equal(blocked.routes.find(r=>r.id==='adjacent').level,'locked');assert(blocked.preview.changes[0].remaining.includes('连续实习安排'));
 const urgent={...demoAnswers,finance:'urgent'},runway=scenarioPlan(urgent,'runway',demoPlan(urgent));assert.equal(runway.routes.find(r=>r.id==='study').level,'alternative');
});
test('通用路线标题不能用具体行动绕开地域、实习和脱产边界',()=>{
 for(const action of ['申请外地的目标岗位','寻找连续实习机会','开始全职备考']){const p=plan();p.routes[0].action.steps[0]=action;assert.throws(()=>guardResult(p,{...demoAnswers,finance:'urgent'}),/硬条件标签/);}
});
test('条件、风险、完成标准与杠杆变化均进入版本差异',()=>{
 const before={answers:demoAnswers,result:plan()},after=structuredClone(before);after.result.routes[0].risk='新发现的风险';after.result.routes[0].conditions.push('新的资格门槛');after.result.routes[0].action.done='新的成果标准';after.result.lever='新的关键条件';
 const changes=planChanges(before,after);assert(changes.some(c=>/风险/.test(c.note)&&/条件/.test(c.note)&&/完成标准/.test(c.note)));assert(changes.some(c=>c.title==='关键杠杆'));assert.deepEqual(planChanges(before,structuredClone(before)),[]);
});
test('模型资料按阶段与领域过滤，引用范围明确且保留历史边界',()=>{
 assert.deepEqual(evidenceForProfile(sampleAnswers('school')).sources,[]);
 assert.deepEqual(evidenceForProfile({...demoAnswers,major:'design'}).sources.map(s=>s.id),['study_policy','study_sample']);
 const pack=evidenceForProfile({...demoAnswers,direction:'ai'});assert(pack.sources.some(s=>s.id==='ai'));assert(!pack.sources.some(s=>['java','data'].includes(s.id)));assert.match(pack.scope,/尚未按目标城市/);
});
test('旧规划没有核心矛盾也可连续保存读取，历史行动仍在',()=>{
 const raw=plan();delete raw.coreConflict;const a=cleanRecord({id:'legacy-record',answers:demoAnswers,result:raw,work:{practice:{completed:[0],notes:{proof:'旧成果'}}}}),state={...emptyStore(),plans:[a]};
 const first=decodeStore(JSON.stringify(state)),second=decodeStore(JSON.stringify(first));assert.equal(second.plans[0].result.coreConflict,'');assert.equal(second.plans[0].work.practice.notes.proof,'旧成果');
});

test('边界说明中的明确否定不误判为越界行动，后续实际越界指令仍被拦截',()=>{
 const p=plan();p.routes[0].why='你不能接受外地，目前先在本地对照目标任务。';assert.doesNotThrow(()=>guardResult(p,demoAnswers));
 p.routes[0].action.steps[0]='申请异地的实习岗位';assert.throws(()=>guardResult(p,demoAnswers),/硬条件标签/);
});
