import {questions,buildProfile,demoPlan} from '../public/core.js';
export function validateDraft(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('草稿格式不正确。');const a={};for(const q of questions){if(raw.answers?.[q.id]===undefined)continue;const v=raw.answers[q.id];if(typeof v!=='string'||(q.type==='text'?v.length>q.limit:!q.options.some(o=>o.value===v)))throw Error('草稿含无效答案。');a[q.id]=v;}return {answers:a,index:Number.isInteger(raw.index)?Math.max(0,Math.min(raw.index,20)):0,confirmed:raw.confirmed===true,mode:raw.mode==='demo'?'demo':'live',isDemo:raw.isDemo===true};}
export async function sha256(text){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(n=>n.toString(16).padStart(2,'0')).join('');}
export async function sessionFor(request,db){const cookie=request.headers.get('Cookie')||'',match=cookie.match(/(?:^|;\s*)lc_session=([A-Za-z0-9_-]{43})(?:;|$)/);if(match){const hash=await sha256(match[1]);const row=await db.prepare('SELECT id FROM sessions WHERE id=? AND expires_at > ?').bind(hash,new Date().toISOString()).first();if(row)return {id:hash,cookie:null};}const bytes=crypto.getRandomValues(new Uint8Array(32));const token=btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const id=await sha256(token),created=new Date().toISOString(),expires=new Date(Date.now()+30*86400000).toISOString();await db.prepare('INSERT INTO sessions(id,created_at,expires_at) VALUES(?,?,?)').bind(id,created,expires).run();return {id,cookie:'lc_session='+token+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000'+(new URL(request.url).protocol==='https:'?'; Secure':'')};}
export async function saveDraft(db,owner,state){const draft=validateDraft(state);await db.prepare('INSERT INTO drafts(session_id,state_json,updated_at) VALUES(?,?,?) ON CONFLICT(session_id) DO UPDATE SET state_json=excluded.state_json,updated_at=excluded.updated_at').bind(owner,JSON.stringify(draft),new Date().toISOString()).run();return draft;}
export async function readDraft(db,owner){const row=await db.prepare('SELECT state_json FROM drafts WHERE session_id=?').bind(owner).first();return row?JSON.parse(row.state_json):null;}
export async function savePlan(db,owner,answers,result){const id=crypto.randomUUID(),created=new Date().toISOString();await db.batch([db.prepare('INSERT INTO plans(id,session_id,title,answers_json,result_json,mode,created_at) VALUES(?,?,?,?,?,?,?)').bind(id,owner,result.summary,JSON.stringify(answers),JSON.stringify(result),result.mode,created),db.prepare('DELETE FROM drafts WHERE session_id=?').bind(owner)]);return {id,created};}
export async function getPlan(db,owner,id){const row=await db.prepare('SELECT id,title,answers_json,result_json,mode,created_at FROM plans WHERE id=? AND session_id=?').bind(id,owner).first();if(!row)return null;const work=await db.prepare('SELECT route_id,completed_json,notes_json,revision FROM actions WHERE plan_id=?').bind(id).all();return {id:row.id,answers:JSON.parse(row.answers_json),result:JSON.parse(row.result_json),mode:row.mode,created:row.created_at,actions:work.results.map(r=>({routeId:r.route_id,completed:JSON.parse(r.completed_json),notes:JSON.parse(r.notes_json),revision:r.revision}))};}
export async function history(db,owner){return (await db.prepare('SELECT id,title,mode,created_at FROM plans WHERE session_id=? ORDER BY created_at DESC LIMIT 25').bind(owner).all()).results;}
export async function saveAction(db,owner,id,body){const plan=await getPlan(db,owner,id);if(!plan)throw Error('这份规划不属于当前浏览器。');if(typeof body.routeId!=='string'||!plan.result.routes.some(r=>r.id===body.routeId))throw Error('行动路线不存在。');const route=plan.result.routes.find(r=>r.id===body.routeId);if(!Array.isArray(body.completed)||body.completed.length>5||body.completed.some(i=>!Number.isInteger(i)||i<0||i>=route.action.steps.length))throw Error('行动进度格式不正确。');const notes={};for(const k of ['source','proof','feedback','next']){const v=body.notes?.[k]??'';if(typeof v!=='string'||v.length>1200)throw Error('行动记录过长。');notes[k]=v;}if(!Number.isInteger(body.revision)||body.revision<0)throw Error('行动版本不正确。');
  const existing=plan.actions.find(a=>a.routeId===body.routeId);const completed=[...new Set(body.completed)].sort((a,b)=>a-b);if(existing&&JSON.stringify([...existing.completed].sort((a,b)=>a-b))===JSON.stringify(completed)&&JSON.stringify(existing.notes)===JSON.stringify(notes))return {revision:existing.revision,reused:true};if((existing?.revision||0)!==body.revision)throw Error('记录已在其他标签页更新，请重新打开规划后再保存。');
  const result=await db.prepare('INSERT INTO actions(plan_id,route_id,completed_json,notes_json,revision,updated_at) VALUES(?,?,?,?,1,?) ON CONFLICT(plan_id,route_id) DO UPDATE SET completed_json=excluded.completed_json,notes_json=excluded.notes_json,revision=actions.revision+1,updated_at=excluded.updated_at WHERE actions.revision=?').bind(id,body.routeId,JSON.stringify([...new Set(body.completed)]),JSON.stringify(notes),new Date().toISOString(),body.revision).run();if(result.meta.changes===0)throw Error('记录已在其他标签页更新，请重新打开规划后再保存。');return {revision:body.revision+1};}
export async function allowance(db,owner,ip,secret){const bucket=new Date().toISOString().slice(0,10),ipScope=await sha256(secret+'|'+ip);const results=await db.batch([db.prepare('INSERT INTO usage_windows(scope,bucket,requests) VALUES(?,?,1) ON CONFLICT(scope,bucket) DO UPDATE SET requests=requests+1 WHERE requests < 20').bind(owner,bucket),db.prepare('INSERT INTO usage_windows(scope,bucket,requests) VALUES(?,?,1) ON CONFLICT(scope,bucket) DO UPDATE SET requests=requests+1 WHERE requests < 60').bind('ip:'+ipScope,bucket)]);return results.every(r=>r.meta.changes===1);}
export async function cleanup(db){let removed=0;for(let page=0;page<20;page++){const expired=(await db.prepare('SELECT id FROM sessions WHERE expires_at < ? LIMIT 100').bind(new Date().toISOString()).all()).results;if(!expired.length)break;await db.batch(expired.map(r=>db.prepare('DELETE FROM sessions WHERE id=?').bind(r.id)));removed+=expired.length;if(expired.length<100)break;}await db.prepare('DELETE FROM usage_windows WHERE bucket < ?').bind(new Date(Date.now()-3*86400000).toISOString().slice(0,10)).run();await db.prepare('DELETE FROM planning_jobs WHERE expires_at < ?').bind(Date.now()-86400000).run();return {removed};}
export async function acquireJob(db,owner,requestId,fingerprint){
 if(typeof requestId!=='string'||!/^[a-f0-9-]{36}$/.test(requestId))throw Error('分析请求标识格式不正确。');
 const now=Date.now();await db.prepare("UPDATE planning_jobs SET status='failed' WHERE session_id=? AND status='running' AND expires_at < ?").bind(owner,now).run();
 const insert=await db.prepare("INSERT OR IGNORE INTO planning_jobs(session_id,request_id,fingerprint,status,created_at,expires_at) VALUES(?,?,?,'running',?,?)").bind(owner,requestId,fingerprint,now,now+240000).run();
 if(insert.meta.changes===1)return {acquired:true};
 const existing=await db.prepare('SELECT fingerprint,status,result_plan_id FROM planning_jobs WHERE session_id=? AND request_id=?').bind(owner,requestId).first();
 if(existing&&existing.fingerprint!==fingerprint)throw Error('分析请求内容与原版本不一致。');
 return {acquired:false,status:existing?.status||'running',planId:existing?.result_plan_id||null};
}
export async function finishJob(db,owner,requestId,planId=null,failed=false){await db.prepare('UPDATE planning_jobs SET status=?,result_plan_id=?,expires_at=? WHERE session_id=? AND request_id=?').bind(failed?'failed':'completed',planId,Date.now()+86400000,owner,requestId).run();}
export {buildProfile,demoPlan};
